export const ROUTES = {
  HOME: '/',
  CATALOG: '/programas',
  COURSE: '/programas/:slug',
  ABOUT: '/nosotros',
  BLOG: '/blog',
  BLOG_POST: '/blog/:slug',
  MULTIMEDIA: '/multimedia',
  PROFESSORS: '/profesores',
  PROFILE: '/perfil',
  TEACHER_PROFILE: '/profesores/:slug',
  CONTACT: '/contacto',
  LOGIN: '/login',
  REGISTER: '/registro',
  PRIVACY: '/privacidad',
  TERMS: '/terminos',
  COOKIES: '/cookies',
} as const;
